name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Example hello-cargo Build
      run: cargo build --verbose
      working-directory: examples/hello-cargo
    - name: Example iron-gcd Build
      run: cargo build --verbose
      working-directory: examples/iron-gcd
    - name: Example mandelbrot-plot Build
      run: cargo build --verbose
      working-directory: examples/mandelbrot-plot
    - name: Example mandelbrot-plot Run tests
      run: cargo test --verbose
      working-directory: examples/mandelbrot-plot